[package]
name = "duktape-sys"
version = "0.1.0"
authors = ["Nathan Moos <moosingin3space@gmail.com>"]
links = "duktape"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.17.0"
gcc = "0.3"
